# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82739d497f9acc7d9484e8a2fdde02bb268195caf632a9d8371e075d35543b1a9c52ba00b6475b31d1c9d2e263a724159145da5b7f24742aeb66f2146298334f

test:
  secret_key_base: a6b146cba9af5078d7c67cead40563891135ed2dcc2f07b6cb3746f530d0c08166967d2653e21ecd4615380a37629b19c75de5d38150dee3d77162218676c1ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
